Fixes (#50)
* Dark UI & Enhanced Interface (#49)

* Update Readme and Generate UI, startup fix (#48)

* Fixes startup error in FreeCAD 0.20

Error: "cannot import name 'QtWidgets' from 'PySide'"
Solution: PySide2.QtWidgets classes are placed in the PySide.QtGui namespace (https://wiki.freecad.org/PySide)

* Update README.md

- Flow chart changed for readability on dark background
- Added links
- Clarifications in usage

* More robust usage of file paths

* Rework of Generate UI

- Improved switching through the generations
- FreeCAD progress bar added
- Code simplifications and responsive design

* version number changed

---------

Co-authored-by: Steven Quirin <102602077+s-quirin@users.noreply.github.com>

* Tree view behaviour and Icon fixes

- Tree view behaviour: Always add object to workbench group in tree view. Moved from Initiate/Generate to Common.py. Fixed group icon.
- Match Initiate icon in toolbar with Spreadsheet icon
- Common.py: Unified Qt namespace

* Beso UI layout code tweak

- Nesting of layouts reduced
- Analysis file path made read-only

* Beso UI separators fixed

Issue: Horizontal lines do not show up and throw "Empty widget item in QVBoxLayout 'verticalLayout'." warning
Solution: Replaced by QFrame

* Fix for FreeCAD#10460

Added methods 'dumps' and 'loads' to the ViewProvider for FreeCAD >= 0.21.2

* Fix for FreeCAD#10460

Added methods 'dumps' and 'loads' to the ViewProvider for FreeCAD >= 0.21.2

---------

Co-authored-by: Serdar Turgut İnce <serince@outlook.com>